### ISSUE TITLE
Not Dart compatible

### ISSUE THREAD

**Issue by JCKodel** [jankuss/genq#19]
Error when parsing: lib\features\auth\entities\app_theme.dart:13
>  final class AppTheme with _$AppTheme implements ISerializable, ICopyWith<AppTheme> {
>  ^
>  Unexpected token: FINAL (`final`). Expected CLASS.
✅ Generated 0 data classes

Dart is not JavaScript, we have final, abstract interface, abstract base and sealed classes.

**Comment by jankuss** [comment]
indeed, right now genq expects the class keyword right after annotation. We should support different class modifiers though, I'll implement a fix.

**Comment by jankuss** [comment]
We can extend the parser to support class modifiers. The analyzer would still not be happy with the generated output though.

Take this example:

```dart
@freezed
final class Geo with _$Geo {
  factory Geo({
    required String lat,
    required String lng,
  }) = _Geo;
}
``` 

The generated `_Geo` constructor needs to `implement` from `Geo`:

```dart
abstract class _Geo implements Geo { /* ... */
```

If `Geo` is a `final class`, this is not valid dart code. We probably need to put this final modifier in the generated classes as well to avoid the error:

```
bin/json.freezed.dart:130:16 • The type '_Geo' must be 'base', 'final' or 'sealed' because the supertype 'Geo' is 'final'
```

**Comment by JCKodel** [comment]
Don't bother.

Even equality isn't functional (the generated code only checks for reference equality, defeating the whole purpose of value equality).

**Comment by jankuss** [comment]
> Don't bother.
> 
> Even equality isn't functional (the generated code only checks for reference equality, defeating the whole purpose of value equality).

@JCKodel this is not true - the generated equality operator checks for value equality for each field in the data class.

```
  final user1 = User(id: 1, name: 'JCKodel', address: Address(zip: '12345'));
  final user2 = User(id: 1, name: 'JCKodel', address: Address(zip: '12345'));

  print(user1 == user2); // This will print true
```

This even holds true for lists/sets/maps

```
  final user1 = User(id: 1, name: 'JCKodel', addresses: [Address(zip: '12345')]);
  final user2 = User(id: 1, name: 'JCKodel', addresses: [Address(zip: '12345')]);

  print(user1 == user2); // This will print true
```

Do you have an example where this breaks for you? Are you sure you are not accidentally using another class which does not support value equality?
